function processFlow(wf, d, tres)
% processFlow to analyze flow waveforms generated by the QVT tool or from
% other sources
% wf: "raw" velocities
%   dimensions npts x ntimes 
%   rows are the centerline points 
%   columns are the time frames 
% d: 
%   column vector, height npts 
%   contains the distance along the vessel from an arbitrary origin, in mm
% tres: scalar, time in ms between frames
%
% note the output of MATLAB size() function is nrows followed by ncolumns,
% and when labeling an array element, the first index is the row number.

norder = 3;
nfunc = 2*norder + 1;

[ npts, ntms ] = size(wf);
ntminterp = 200;

% we probably need these sometime ...
tvec = (1:ntms)*tres;
T = tvec(end);
tvecinterp = (1:ntminterp)*(T/ntminterp);

% we need 4 global fits at multiple velocities
% each velocity has a different basis function matrix because velocity is a
% phase shift
% outputs are coefficients of the basis functions and chi squared as
% functions of velocity, and we also need a vector of values of each
% centerline point for plotting
% start with Cecilia's model, no scaling
% start with two velocities, 5 m/s and 10 m/s
% basis functions depend on velocity so we put everything in a loop on
% velocity
% basis functions will be put in 3-d matrices where row is function index,
% column is time frame, and page in centerline point
% we will need interpolated "curves" at each velocity
% we won't save the coefficients past the loop
% inversepwv = (4:9)/10;
inversepwv = [ 0, 0.007, 0.01, 0.014, 0.02, 0.03, 0.05, 0.07, 0.1, ...
    0.14, 0.2, 0.3, 0.5, 0.7, 1, 1.4 ];
numpwv = length(inversepwv);
pwvlnstyles = { 'b-', 'g-', 'm-', 'k-', 'r--', 'b--', 'g--', 'm--', ...
    'k--', 'r-.', 'b-.', 'g-.', 'm-.', 'k-.' }; % 14 options!
idxplotpwv = 1:4:numpwv;
numplottedpwv = length(idxplotpwv);
if numplottedpwv > 14
    disp('programming error, you need more line styles')
    return
end
swedenNoScaleWaveforms = zeros(numpwv,npts,ntminterp);
swedenNoScaleChisq = zeros(1,numpwv);
swedenScaledFitWaveforms = swedenNoScaleWaveforms;
swedenScaledFitChisq = swedenNoScaleChisq;
for idxv = 1:numpwv
    % initialize basis functions
    % basis functions don't depend on whether I do the rescaling
    BasFuncSweden = zeros(ntms,npts,ntms);
    % BasFuncSwedeInterp = zeros(ntms,npts,ntminterp);
    for idxbasfunc = 1:ntms
        for idxpt = 1:npts
            % seems like there's an easier MATLAB-way to do this
            tctr = tvec(idxbasfunc) + d(idxpt)*inversepwv(idxv);
            BasFuncSweden(idxbasfunc,idxpt,:) = trianglebasisfunc(tvec, tctr, tres);
            % BasFuncSwedeInterp(idxbasfunc,idxpt,:) = trianglebasisfunc(tvecinterp, tctr, tres);
        end
    end
    bfreshape = reshape(BasFuncSweden,ntms,npts*ntms);
    A = bfreshape*bfreshape';

    % we will do both unscaled and scaled calculations in the same loop 
    Bnoscale = zeros(ntms,1);
    Bscaledfit = zeros(ntms,1);
    [ wfscalefactors, wfoffsets ] = std(wf,0,2);
    % is there a better way to do this?
    % we calculate both B vectors in the same loop
    for idxbasfunc = 1:ntms
        for idxpt = 1:npts
            for idxtm = 1:ntms
                Bnoscale(idxbasfunc) = Bnoscale(idxbasfunc) + ...
                    wf(idxpt,idxtm)*BasFuncSweden(idxbasfunc,idxpt,idxtm);
                Bscaledfit(idxbasfunc) = Bscaledfit(idxbasfunc) ...
                    + (wf(idxpt,idxtm) - wfoffsets(idxpt))/wfscalefactors(idxpt) ...
                    *BasFuncSweden(idxbasfunc,idxpt,idxtm);
            end
        end
        % I tried this but forgot to reshape the basis function matrix
        % B(idxbasfunc) = squeeze(sum(wf.*BasFuncSwedenNoScale(:,:,idxbasfunc),'all'));
    end

    wfnoscalemod = A\Bnoscale;
    wfscaledfit = A\Bscaledfit;
    chisqnoscale = 0;
    chisqscaledfit = 0;
    for idxpt = 1:npts
        toffset = d(idxpt)*inversepwv(idxv);

        ynoscale = zeros(1,ntminterp);
        yscaledfit = zeros(1,ntminterp);
        for idxfun = 1:ntms
            f = trianglebasisfunc(tvecinterp,tvec(idxfun)+toffset,tres);
            ynoscale = ynoscale + f*wfnoscalemod(idxfun);
            yscaledfit = yscaledfit + f*wfscaledfit(idxfun);
        end
        swedenNoScaleWaveforms(idxv,idxpt,:) = ynoscale;
        swedenScaledFitWaveforms(idxv,idxpt,:) ...
            = wfscalefactors(idxpt)*yscaledfit + wfoffsets(idxpt);

        % repeat for calculating chi squared
        ynoscale = zeros(1,ntms);
        yscaledfit = zeros(1,ntms);
        for idxfun = 1:ntms % because ntms is also the number of basis functions
            f = trianglebasisfunc(tvec,tvec(idxfun)+toffset,tres);
            ynoscale = ynoscale + f*wfnoscalemod(idxfun);
            yscaledfit = yscaledfit + f*wfscaledfit(idxfun);
        end
        chisqnoscale = chisqnoscale + sum((ynoscale - wf(idxpt,:)).^2);
        chisqscaledfit = chisqscaledfit + sum((wf(idxpt,:) ...
            - (yscaledfit*wfscalefactors(idxpt) + wfoffsets(idxpt))).^2);
    end
    swedenNoScaleChisq(idxv) = chisqnoscale;
    swedenScaledFitChisq(idxv) = chisqscaledfit;
end

% setting up for fits of individual centerline points

% create a matrix nfunc x ntms representing the basis functions
% rows will represent a basis function
% columns will represent the function arguments, evenly spaced, scaled up
% to 2*pi as follows:
tscaled = (2*pi/ntms)*(1:ntms);
BasisFuncs = ones(nfunc,ntms); % correct for BasisFuncs(1,:)
tinterpscaled = (1:ntminterp)*(2*pi/ntminterp);
BasFuncInterp = ones(nfunc,ntminterp);
for k = 1:norder
    for idxtm = 1:ntms
        x = k*tscaled(idxtm);
        BasisFuncs(2*k,  idxtm) = cos(x);
        BasisFuncs(2*k+1,idxtm) = sin(x);
    end
    for idxtm = 1:ntminterp
        x = k*tinterpscaled(idxtm);
        BasFuncInterp(2*k,  idxtm) = cos(x);
        BasFuncInterp(2*k+1,idxtm) = sin(x);
    end
end


% goal is to solve Ax = B for x. A only depends on the number of time
% frames, not the measured velocities. x will be a column vector
A = BasisFuncs*BasisFuncs';
xcoef = zeros(npts,nfunc);

% loop over centerline points
for ipt = 1:npts    
    Bnoscale = zeros(nfunc,1);
    for idxtm = 1:ntms
        for ii = 1:nfunc
            Bnoscale(ii) = Bnoscale(ii) + wf(ipt,idxtm)*BasisFuncs(ii,idxtm);
        end
    end
    xcoef(ipt,:) = A\Bnoscale; % these should be the coefficients
    wffourier = sum(xcoef(ipt,:).*BasFuncInterp',2);

    % only have the waveforms are plotted in the call below, that wasn't
    % changed here yet
    % plothelper(tvecinterp,wffourier,tvec,wf(ipt,:), ...
    %     squeeze(swedenNoScaleWaveforms(:,ipt,:)), ...
    %     inversepwv,pwvlnstyles,d(ipt),'waveforms, scale not allowed in fit,')

    plothelper(tvecinterp,wffourier,tvec,wf(ipt,:), ...
        squeeze(swedenScaledFitWaveforms(idxplotpwv,ipt,:)), ...
        inversepwv(idxplotpwv),pwvlnstyles,d(ipt),...
        'waveforms, data scaled before fit,')
end

% plot coefficients vs. distance, what else?
figure
plot(d,xcoef(:,1),'ro-')
legend('A_0')
xlabel('distance (mm)')
ylabel('coefficient')
title('Fourier coefficient A_0')

% Assume it's A_k cos(kt) + B_k sin(kt)
% then the zeroth order is A_0 cos(0)

magcoef = zeros(npts,norder);
for k = 1:norder
    figure
    A = xcoef(:,2*k);
    Bnoscale = xcoef(:,2*k+1);
    magcoef(:,k) = sqrt(A.*A + Bnoscale.*Bnoscale);
    plot(d,A,'ro-',d,Bnoscale,'bo-',d,magcoef(:,k),'go-')
    legend(sprintf('$A_%d$',k),sprintf('$B_%d$',k),...
        sprintf('$\\sqrt{A_%d^2 + B_%d^2}$',k,k),...
        'Interpreter','latex')
    xlabel('distance (mm)')
    ylabel('coefficient')
    title(sprintf('Fourier coefficients of order %d',k))
end

lnstyle = { 'ro-', 'go-', 'bo-', 'ko-' };
figure
for k = 2:norder
    plot(d,magcoef(:,k)./magcoef(:,1),lnstyle{k-1},'DisplayName',...
        sprintf('$\\sqrt{\\frac{A_%d^2 + B_%d^2}{A_1^2 + B_1^2}}$',k,k))
    hold on
end
% I fixed how the legend is created but did not test it. 
legend('Interpreter','latex')
xlabel('distance (mm)')
ylabel('ratio')
title('ratio of coefficients')

hold off

ttptms = zeros(1,npts);
ttutms = ttptms;
for k = 1:npts
    [ tmax, ~ ] = maxFromFourierDecomp(xcoef(k,:));
    ttptms(k) = tmax(1);
    if length(tmax) > 1
        fprintf('point %d has multiple peaks', k)
        disp(tmax)
    end
    % compute first derivative coefficients
    ddxcoef = derivativeCoefs(xcoef(k,:));
    [ tmax, ~ ] = maxFromFourierDecomp(ddxcoef);
    ttutms(k) = tmax(1);
    if length(tmax) > 1
        fprintf('point %d has multiple maxima of derivative', k)
        disp(tmax)
    end
end

tmscale = T/(2*pi);
figure
plot(d,ttptms*tmscale,'ro')
xlabel('distance (mm)')
ylabel('time (ms)')
title('Time to Peak')

figure
plot(d,ttutms*tmscale,'go')
xlabel('distance (mm)')
ylabel('time (ms)')
title('Time to Upslope')

figure
plot(inversepwv,swedenNoScaleChisq,'ro')
xlabel('reciprocal pulse wave velocity (s/m)')
ylabel('$\chi^2$','Interpreter','latex')
title('sum of least squares for unscaled fit')

figure
plot(inversepwv,swedenScaledFitChisq,'ro')
xlabel('reciprocal pulse wave velocity (s/m)')
ylabel('$\chi^2$','Interpreter','latex')
title('sum of least squares when fitting scaled waveforms')

function [ tmax, ymax ] = maxFromFourierDecomp(coefvec)
% maximum of a function A_0 + \Sigma_k (A_k cos(kt) + B_k sin(kt))
% coefvec(1) = A_0
% coefvec(2*k) = A_k
% coefvec(2*k+1) = B_k for k >= 1
% independent variable has the range [ 0, 2*pi )
% vmax is the value at tmax
% caller should scale tmax to time in milliseconds (or whatever)
% multiple maxima can be returned so caller can check if two local maxima
% are too similar

% check for valid input length
nfun = length(coefvec);
if mod(nfun,2) ~= 1
    error('FourierEval:InvalidCoefVector',...
        'Coefficient vector for Fourier series must have an odd length')
end

% a small shift in the independent variable
feps = 0.0001;

% coefficients for first derivative
derivcoef = derivativeCoefs(coefvec);
fundydt = @(x) FourierSeries(x,derivcoef);

% set up arrays & other 
tvec = (2*pi/100)*(0:99);
ntestrng = length(tvec);
tzeroxes = zeros(2,ntestrng);
nzxes = 0;

% start with bin -1 (same as last bin)
tlast = tvec(ntestrng);
dydtlast = fundydt(tlast);
if dydtlast == 0 % will get this at the end
    tlast = tlast + feps;
    dydtlast = fundydt(tlast);
end
for k = 1:ntestrng
    t = tvec(k);
    dydt = fundydt(t);
    if dydt == 0
        nzxes = nzxes + 1;
        tzeroxes(1,nzxes) = t;
        tzeroxes(2,nzxes) = t;
        tlast = t + feps;
        dydtlast = fundydt(tlast);
        continue
    end
    if dydtlast*dydt < 0 % then they must have opposite signs
        nzxes = nzxes + 1;
        tzeroxes(1,nzxes) = tlast;
        tzeroxes(2,nzxes) = t;
    end
    tlast = t;
    dydtlast = dydt;
end

% now find precise zero crossings and then determine if they are
% maxima or minima
ttmpmax = zeros(1,nzxes);
ytmpmax = ttmpmax;
nmaxima = 0;
for k = 1:nzxes
    if abs(tzeroxes(1,k) - tzeroxes(2,k)) < feps*feps
        ttmp = tzeroxes(1,k);
        if fundydt(ttmp-feps)*fundydt(ttmp+feps) >= 0
            % possibly an inflection point, not an extremum
            continue
        end
    else
        ttmp = fzero(fundydt,tzeroxes(:,k));
    end
    % confirm this is a maximum
    ytmp = FourierSeries(ttmp,coefvec);
    if ytmp > FourierSeries(ttmp-feps,coefvec) ...
            && ytmp > FourierSeries(ttmp+feps,coefvec)
        nmaxima = nmaxima + 1;
        ttmpmax(nmaxima) = ttmp;
        ytmpmax(nmaxima) = ytmp;
    end
end

if nmaxima < 1
   error('FourierEval:MaxFail',...
        'Found no maxima in Fourier series')
end

if nmaxima == 1
    tmax = ttmpmax(1);
    ymax = ytmpmax(1);
else
    % need to sort
    [ ymaxsrt, idxvec ] = sort(ytmpmax,'descend');
    tmaxsrt = ttmpmax(idxvec);
    % threshold is 90% of distance between mean and global max
    idxvec = find(ymaxsrt > 0.9*ymaxsrt(1) + 0.1*coefvec(1));
    if length(idxvec) > 1
        for kk = length(idxvec):-1:2
            if abs(tmaxsrt(kk) - tmaxsrt(kk-1)) < 1e-6
                idxvec(kk) = [];
            end
        end
    end
    tmax = tmaxsrt(idxvec);
    ymax = ymaxsrt(idxvec);
end

function y = FourierSeries(t, fcoef)
% helper for maxFromFourierDecomp()

% assume this is only called by maxFromFourierDecomp, which does this check
% nfun = length(fcoef);
% if mod(nfun,2) ~= 1
%     error('FourierEval:InvalidCoefVector',...
%         'Coefficient vector for Fourier series must have an odd length')
% end
norder = (length(fcoef) - 1)/2;
y = fcoef(1);
for k = 1:norder
    y = y + fcoef(2*k)*cos(k*t) + fcoef(2*k+1)*sin(k*t);
end

function ddxcoef = derivativeCoefs(x)

dim = size(x);
ddxcoef = zeros(dim);
norder = (length(x) - 1)/2;
if norder ~= floor(norder)
    error('FourierEval:InvalidCoefVector',...
        'Coefficient vector for Fourier series must have an odd length')
end
for k = 1:norder
    idxcos = 2*k;
    idxsin = idxcos + 1;
    ddxcoef(idxcos) = k*x(idxsin);
    ddxcoef(idxsin) = -k*x(idxcos);
end

function y = trianglebasisfunc(tvec, tctr, tr)
% arguments are a vector of times, the "center time" for this basis
% function, and resolution tr
% assume tvec = (1:n)*some_factor so that period = tvec(end)

y = zeros(size(tvec));
T = tvec(end);
toffset = abs(tvec - tctr);
while true
    idxwrap = find(toffset > T/2);
    if isempty(idxwrap) ; break ; end
    toffset(idxwrap) = abs(toffset(idxwrap) - T);
end
idx = find(toffset < tr);
y(idx) = 1 - toffset(idx)/tr;


function plothelper(tvfine,yfine,tv,ydata,pwvwfs,invpwv,lnstyle,x,lblpfix)

numpwv = length(invpwv);
figure
plot(tvfine,yfine,'r-','DisplayName','Fourier decomposed')
hold on
plot(tv,ydata,'ro','DisplayName','raw data')
for ivel = 1:numpwv
    slbl = sprintf('Fit 1/v = %.3f s/m',invpwv(ivel));
    plot(tvfine,pwvwfs(ivel,:),lnstyle{ivel},'DisplayName',slbl)
end
legend
xlabel('Time (ms)')
ylabel('Flow (mL/sec) (check!)')
title(sprintf('%s at d = %.2f mm',lblpfix,x))

